### ISSUE TITLE
Enable UDP for egress traffic on Azure

### ISSUE THREAD

**Issue by zanetworker** [gardener/gardener-extension-provider-azure#1]
Currently we have a problem that if  **standard** loadbalancers are used, no frontend ip configuration will be created for UDP by default which in turns will result in blockage for all UDP egress requests (e.g., NTP, DNS,  etc.). 

To fix this we need to support UDP egress traffic. This can be done either via a real NAT GW (not using the LB as a GW), or by modifying any of the shoot services created on the `kube-system` namespace to also have a UDP port. 

cc @dkistner

**Comment by tim-ebert** [comment]
I added a temporary fix for this issue in #32 

This will add a Service called `allow-udp-egress` with a single UPD port to the `kube-system` namespace of Shoots using Azure Standard LoadBalancers (e.g. Zoned Shoot clusters).
It is needed because the Standard LoadBalancers will block all outgoing UDP traffic if there is not at least one open UDP Port.

This workaround will be removed in a future version, once we have a proper implemenation for UDP egress via an Azure NAT Gateway in place.

**Comment by dkistner** [comment]
I would consider the solution with the `allow-udp-egress` as only way to guarantee udp traffic  in all scenarios. We do not enforce the usage of a natgateway and we will get rid of the basic loadbalancer when we replacing availablitysets with vmo. I guess we will then always have a standard loadbalancer, but a natgateway is only there when the user  configure it (e.g egress needs stable ip). Therefore I would like to stay with the udp service solution for all scenarios to ensure that udp egress is working.

/close
