### ISSUE TITLE
When "infrastructureConfig" has invalid format user can't see the actual error.

### ISSUE THREAD

**Issue by vlvasilev** [gardener/gardener-extension-provider-azure#232]
**How to categorize this issue?**

/area logging
/kind enhancement
/priority normal
/platform azure

**What would you like to be added**:
When validating the `infrastructureConfig` the validating controller shows only `not allowed to configure an unsupported infrastructureConfig`.
It will be a good to add more verbose error message to show the user what and where exactly is the error.

**Why is this needed**:
If a client has misconfigured  "infrastructureConfig" section in the shoot specification, the only message he gets is 
```
spec.provider.infrastructureConfig: Forbidden: not allowed to configure an unsupported infrastructureConfig"
```
and he is unable see his misconfiguration.
The issue comes from a client which is using go library to generate and apply the shoot spec.
According to his example, the only missing thing was the apiVersion and Kind which he told me that are inserted automatically before Create request. Everything else seem to be properly configured. 
There was no example of the misconfigured `infrastructureConfig` in the error message in the validating controller, nor a concrete error denoting the misconfiguration.
According to the code snipped:
```
infraConfig, err := decodeInfrastructureConfig(decoder, config)
if err != nil {
return nil, field.Forbidden(infraConfigPath, "not allowed to configure an unsupported infrastructureConfig")
}
```
the actual error is skiped.

**Comment by ialidzhikov** [comment]
I believe the error is clear enough. Please try to add `apiVersion` and `kind` to the infrastructureConfig.

/close

**Comment by kon-angelo** [comment]
To add a little bit more context: 

There is more fine-grained validation for the `infrastructureConfig` but this happens after the object has been decoded to its Go struct. To do the decode we need to know the `ApiVersion` and `Kind`, because after all we need to know the type of the object we try to decode.  

Here the error seems to happen during this yaml -> Go decoding and its highly indicative that the ApiVersion and Kind were not present at all. The messages after this point are usually more detailed about what is wrong with the configuration.
