### ISSUE TITLE
Support PremiumV2_LRS storage 

### ISSUE THREAD

**Issue by ewuknadierf** [gardener/gardener-extension-provider-azure#633]
**How to categorize this issue?**
/area storage
/kind enhancement
/platform azure

**What would you like to be added**:
Gardener should support PremiumV2_LRS for node VMs.
https://learn.microsoft.com/en-us/azure/aks/azure-disk-csi#storage-class-driver-dynamic-disks-parameters

**Why is this needed**:
For cost and performance improvements.

**Comment by kon-angelo** [comment]
@ewuknadierf Reading https://learn.microsoft.com/en-us/azure/virtual-machines/disks-types#premium-ssd-v2-limitations more closely it seems like PremiumV2_LRS cannot be used for VM root disks. You are only able to use it via CSI which should already be supported in the latest release of the provider even if you would need to create your own storage class to do so.

Because of the limitations I would also be reluctant to create a managed storage class at the moment and I feel it would be better if you would manage it on your own.

**Comment by ewuknadierf** [comment]
thxs for clarification @kon-angelo!
/close
