### ISSUE TITLE
Integrate vSMP MemeoryOne in Azure

### ISSUE THREAD

**Issue by sameach23** [gardener/gardener-extension-provider-azure#788]
How to categorize this issue?

/area usability
/area os
/kind enhancement

What would you like to be added:
Gardener already supports multi-volume connection for machines used by MemeoryONE in AWS , to boot OS and MemeoryOne software on the same worker-node on separate dataVolumes.
The same functionality needed in Azure for MemoryONE worker-nodes.

I would post here a link to an epic for the similar functionality requested in AWS in the past.
https://github.com/gardener/gardener/issues/2354

Why is this needed:

**Comment by YakovKugel** [comment]
Dear Gardener Team,
The absence of a multi-volume connection in Azure had led to 130 minutes of downtime for EU20, EU21 , Canary-AZ customers in total. This was triggered by the requirement to perform an extra reboot on the VM installed with MemoryONE to avoid a 50% decrease in machine memory size triggered by standard Azure's host OS update. This issue arose due to the availability of just one data volume for the VM in Azure. We kindly request you to elevate the priority level of this task to very high.
https://jira.tools.sap/browse/HC01-210550

**Comment by YakovKugel** [comment]
What is the ETA of that feature in Gardener Live ?

**Comment by YakovKugel** [comment]
@kon-angelo 
Hello Konstantinos, 
We would like to begin our testing in Azure, and it appears that the feature is not merged yet.
Is there any estimation when Gardener would merge this feature?

**Comment by kon-angelo** [comment]
@YakovKugel we wait for feedback by MCM colleagues in the referenced PR.
